
Testing: 0it [00:00, ?it/s]/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/results/HiLo_experiment111/cape/03223-shortshort-squats-000320
Traceback (most recent call last):
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/cephfs/home/dihitalhuman_sx_2024/code/avatar/HiLo/apps/train.py", line 439, in <module>
    trainer.test(model=model, datamodule=datamodule)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 915, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in __test_given_model
    results = self.fit(model)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 540, in dispatch
    self.accelerator.start_testing(self)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 76, in start_testing
    self.training_type_plugin.start_testing(trainer)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 118, in start_testing
    self._results = trainer.run_test()
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 786, in run_test
    eval_loop_results, _ = self.run_evaluation()
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 725, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 160, in evaluation_step
    output = self.trainer.accelerator.test_step(args)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 195, in test_step
    return self.training_type_plugin.test_step(*args)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 134, in test_step
    return self.lightning_module.test_step(*args, **kwargs)
  File "/mnt/cephfs/home/dihitalhuman_sx_2024/code/avatar/HiLo/apps/ICON.py", line 621, in test_step
    os.makedirs(self.export_dir, exist_ok=True)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/mnt/cephfs/home/qiuzhen/anaconda3/envs/icon3090v1/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/cephfs/dataset/NVS/experimental_results/avatar/icon/data/results/HiLo_experiment111'